In [1]:
import tensorflow as tf

In [2]:
print (tf.__version__)

2.2.0


In [3]:
x = tf.constant(range(12))

In [4]:
x

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])>

In [7]:
print(x.shape)

(12,)


In [9]:
x = tf.reshape(x, (3,4))

In [10]:
x

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])>

In [11]:
tf.reshape(x, (-1, 4))

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])>

In [12]:
x = tf.constant([[1,0],[0,1]])

In [14]:
y = tf.constant([[1,2],[3,4]])

In [15]:
x * y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 4]])>

In [18]:
x = tf.ones([3,4])

In [19]:
x


<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [20]:
x = tf.random.normal([3,4])

In [21]:
tf.contact([x,y],axis = 0)

AttributeError: module 'tensorflow' has no attribute 'contact'

In [22]:
tf.concat([x,y],axis = 0)

InvalidArgumentError: cannot compute ConcatV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:ConcatV2] name: concat

In [23]:
x

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.2519458 ,  0.5924191 , -0.52671736, -0.9505422 ],
       [-1.115374  , -0.09863894, -1.2329121 ,  1.2223105 ],
       [ 1.364865  , -1.2322237 ,  0.9386434 ,  0.01074526]],
      dtype=float32)>

In [24]:
y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [25]:
y = tf.random.normal((3,4))

In [26]:
tf.concact([x,y],axis=0)

AttributeError: module 'tensorflow' has no attribute 'concact'

In [27]:
tf.concat([x,y],axis=0)

<tf.Tensor: shape=(6, 4), dtype=float32, numpy=
array([[-0.2519458 ,  0.5924191 , -0.52671736, -0.9505422 ],
       [-1.115374  , -0.09863894, -1.2329121 ,  1.2223105 ],
       [ 1.364865  , -1.2322237 ,  0.9386434 ,  0.01074526],
       [-1.073026  ,  1.9652328 ,  0.47085366, -0.6009628 ],
       [ 0.39406776,  0.03601837,  1.5466565 ,  0.7304115 ],
       [ 0.12163332, -0.9502221 , -0.85607034,  0.23908803]],
      dtype=float32)>

In [28]:
a = tf.reshape(tf.constant(range(3)), (3,1))

In [29]:
b = tf.reshape(tf.constant(range(3)), (3,1))

In [30]:
a,b


(<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
 array([[0],
        [1],
        [2]])>,
 <tf.Tensor: shape=(3, 1), dtype=int32, numpy=
 array([[0],
        [1],
        [2]])>)

In [33]:
b = tf.reshape(tf.constant(range(2)), (2,1))

In [34]:
a,b

(<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
 array([[0],
        [1],
        [2]])>,
 <tf.Tensor: shape=(2, 1), dtype=int32, numpy=
 array([[0],
        [1]])>)

In [36]:
b = tf.reshape(tf.constant(range(2)), (1,2))

In [37]:
a,b

(<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
 array([[0],
        [1],
        [2]])>,
 <tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[0, 1]])>)

In [38]:
a + b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 1],
       [1, 2],
       [2, 3]])>

In [39]:
x[1:3]

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-1.115374  , -0.09863894, -1.2329121 ,  1.2223105 ],
       [ 1.364865  , -1.2322237 ,  0.9386434 ,  0.01074526]],
      dtype=float32)>

In [40]:
x

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.2519458 ,  0.5924191 , -0.52671736, -0.9505422 ],
       [-1.115374  , -0.09863894, -1.2329121 ,  1.2223105 ],
       [ 1.364865  , -1.2322237 ,  0.9386434 ,  0.01074526]],
      dtype=float32)>

In [41]:
x[1,2:3]

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([-1.2329121], dtype=float32)>

In [42]:
x = tf.Variable(x)

In [43]:
x

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[-0.2519458 ,  0.5924191 , -0.52671736, -0.9505422 ],
       [-1.115374  , -0.09863894, -1.2329121 ,  1.2223105 ],
       [ 1.364865  , -1.2322237 ,  0.9386434 ,  0.01074526]],
      dtype=float32)>

In [44]:
x[1,2].assign(9)

<tf.Variable 'UnreadVariable' shape=(3, 4) dtype=float32, numpy=
array([[-0.2519458 ,  0.5924191 , -0.52671736, -0.9505422 ],
       [-1.115374  , -0.09863894,  9.        ,  1.2223105 ],
       [ 1.364865  , -1.2322237 ,  0.9386434 ,  0.01074526]],
      dtype=float32)>